server:
  port: 8080

spring:
  application:
    name: loan-contract-service
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:loan_contracts}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:j20031027}
    driver-class-name: org.postgresql.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
#        enable_lazy_load_no_trans: false
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:defaultSecretKeyWhichShouldBeChangedInProduction}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
  refresh-token:
    expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days in milliseconds

# SMS Configuration
sms:
  api-key: ${SMS_API_KEY}
  base-url: ${SMS_BASE_URL}
  code:
    expiration: 300
#test
# File Storage Configuration
file:
  upload-dir: ${FILE_UPLOAD_DIR:./uploads}
  max-size: ${FILE_MAX_SIZE:10MB}
  allowed-types: ${FILE_ALLOWED_TYPES:pdf,doc,docx,jpg,jpeg,png}

# Logging Configuration
logging:
  level:
    root: INFO
    uz.idimzo: DEBUG
    org.springframework.web: INFO
    org.hibernate: ERROR